# Generated by Django 4.1 on 2023-04-17 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=100)),
                ('location', models.CharField(choices=[('US', 'Spanish Fork'), ('DE', 'Berlin'), ('VN', 'Hanoi')], max_length=100)),
            ],
        ),
    ]
