# Generated by Django 4.1 on 2023-04-18 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_gallery_picture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
